name: ssr_ltp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scipy=1.13.1
  - scikit-learn=1.5.1
  - sympy=1.13.1
  - casadi=3.7.0
  - ax-platform=1.0.0
  - botorch=0.14.0
  - pytorch=2.6.0
  - ipython>=9,<10
  - ipykernel>=7,<8
  - jupyterlab>=4,<5
  